//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_02_NhanVien.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NhanVienRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NhanVienRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EF_02_NhanVien.Resources.NhanVienRes", typeof(NhanVienRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sach trong!.
        /// </summary>
        internal static string DanhSachTrong {
            get {
                return ResourceManager.GetString("DanhSachTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap du an ID:.
        /// </summary>
        internal static string DuAnId {
            get {
                return ResourceManager.GetString("DuAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho va ten khong duoc qua 20 ky tu!.
        /// </summary>
        internal static string ErrDoDaiTen {
            get {
                return ResourceManager.GetString("ErrDoDaiTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten du an khong duoc qua 10 ky tu!.
        /// </summary>
        internal static string ErrDoDaiTenDuAn {
            get {
                return ResourceManager.GetString("ErrDoDaiTenDuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap la so!.
        /// </summary>
        internal static string ErrID {
            get {
                return ResourceManager.GetString("ErrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam sinh phai o trong khoang tu 1970 den 2000!.
        /// </summary>
        internal static string ErrNgaySinh {
            get {
                return ResourceManager.GetString("ErrNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So gio lam phai la so nguyen duong!.
        /// </summary>
        internal static string ErrSoGioLam {
            get {
                return ResourceManager.GetString("ErrSoGioLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho va ten phai co it nhat hai tu!.
        /// </summary>
        internal static string ErrSoTu {
            get {
                return ResourceManager.GetString("ErrSoTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ghi chu: .
        /// </summary>
        internal static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay du an!.
        /// </summary>
        internal static string KhongTimThayDuAn {
            get {
                return ResourceManager.GetString("KhongTimThayDuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay nhan vien!.
        /// </summary>
        internal static string KhongTimThayNhanVien {
            get {
                return ResourceManager.GetString("KhongTimThayNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap mo ta: .
        /// </summary>
        internal static string MoTa {
            get {
                return ResourceManager.GetString("MoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap nhan vien ID: .
        /// </summary>
        internal static string NhanVienId {
            get {
                return ResourceManager.GetString("NhanVienId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so gio lam: .
        /// </summary>
        internal static string SoGioLam {
            get {
                return ResourceManager.GetString("SoGioLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten du an: .
        /// </summary>
        internal static string TenDuAn {
            get {
                return ResourceManager.GetString("TenDuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh cong!.
        /// </summary>
        internal static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
    }
}
